language:
   - cpp

install:
   - sudo apt-get install cmake libgtest-dev
   - cd /usr/src/gtest
   - sudo cmake CMakeLists.txt
   - sudo make
   - sudo cp *.a /usr/lib

before_script:
    - cd project

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - test/tests
