language:
   - cpp

install:
   - sudo apt-get install cmake libgtest-dev
   - cd /usr/src/gtest
   - sudo cmake CMakeLists.txt
   - sudo make
   - sudo cp *.a /usr/lib

script:
    - git submodule init
    - git submodule update
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - test/tests
