language:
   - cpp

install:
   - sudo apt-get install libgtest-dev
   - cd /usr/src/gtest
   - sudo cmake CMakeLists.txt
   - sudo make
   - sudo make install

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - test/tests
